# Generated by Django 2.2.6 on 2019-10-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=600)),
                ('age', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('habitat', models.CharField(blank=True, max_length=250)),
                ('image', models.URLField(blank=True)),
                ('region', models.CharField(max_length=100)),
                ('geological_era', models.CharField(blank=True, choices=[('TRIASIC', 'Triasic'), ('JURASSIC', 'Jurassic'), ('CRETACEOUS', 'Cretaceous')], max_length=300)),
            ],
        ),
    ]
