# Generated by Django 2.2.6 on 2019-10-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinosaur',
            name='age',
        ),
    ]
