# Generated by Django 2.2.6 on 2019-10-29 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='age',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='geological_era',
            field=models.CharField(blank=True, choices=[('TRIASIC', 'Triasic'), ('JURASSIC', 'Jurassic'), ('CRETACEOUS', 'Cretaceous')], max_length=300),
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
