# Generated by Django 2.2.6 on 2019-10-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0002_remove_dinosaur_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5),
        ),
    ]
