# Generated by Django 2.2.6 on 2019-10-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0003_auto_20191029_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinosaur',
            name='habitat',
        ),
    ]
