# Generated by Django 2.2.6 on 2019-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0004_remove_dinosaur_habitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='geological_era',
            field=models.CharField(blank=True, choices=[('TRIASSIC', 'Triasic'), ('JURASSIC', 'Jurassic'), ('CRETACEOUS', 'Cretaceous')], max_length=300),
        ),
    ]
