# Generated by Django 2.2.6 on 2019-10-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0005_auto_20191030_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
