# Generated by Django 2.2.6 on 2019-11-22 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dinosaur', '0006_auto_20191030_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
